name: minds_env
channels:
  - pytorch
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - requests
  - beautifulsoup4
  - tqdm
  - pytorch
  - torchvision
  - plotly
  - python-kaleido
  - transformers
